server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestor
    username: root
    password: cruel123/
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher